[package]
name = "tokenizers" 
version = "0.9.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.140"
tokenizers = {version =" 0.13.2", features = ["default"] }

[registries.crates-io]
# speed up "Updating crates.io index"
protocol = "sparse"
